version: '3.8'

services:
  osint-main:
    build:
      context: .
    command: python3 main.py
    volumes:
      - "C:/Users/Joshw/OneDrive/Desktop/hacket-osint:/app"
    depends_on:
      - subfinder
      - crosslinked

  subfinder:
    build:
      context: ./tools/subfinder
    command: subfinder -d example.com

  crosslinked:
    build:
      context: ./tools/crosslinked
    volumes:
      - ./output:/app/output