version: '3.8'

services:
  osint-main:
    build:
      context: .
    command: python3 main.py
    volumes:
      - "C:/Users/"
    depends_on:
      - subfinder
      - crosslinked
      - checkmdi

  subfinder:
    build:
      context: ./tools/subfinder
    volumes:
      - ./configs:/app/configs
      - ./output:/app/output
    entrypoint: ["/go/bin/subfinder"]

  crosslinked:
    build:
      context: ./tools/crosslinked
    volumes:
      - ./output:/app/output

  checkmdi:
    build:
      context: ./tools/checkmdi
    volumes:
      - ./output:/app/output
    command: ["sleep", "infinity"]
