chaos:
  api_key: "feacc682-0064-40d9-b94e-e4287478164d"

shodan:
  api_key: "YOUR_SHODAN_API_KEY"

subfinder:
  providers:
    - "virustotal"
    - "securitytrails"
    - "chaos"
  api_keys:
    virustotal: "your_virustotal_api_key"
    securitytrails: "key"
    chaos: "key"
